version: "3.8"

services:
  db:
    image: mysql:8
    container_name: iot_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot_db
    volumes:
      - iot_system_dxc_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: iot_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: iot_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/iot_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET: PPp27xSTfBwOpRn4/AV6gPzQSnQg+Oi80KdWfCcuAHs=

volumes:
  iot_system_dxc_db_data: