# Server
server.port=8080

# MySQL DB connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis (optional, only if used)
spring.redis.host=localhost
spring.redis.port=6379

# JWT
jwt.secret=${JWT_SECRET}


# === Redis Config ===
#spring.redis.host=redis
#spring.redis.port=6379

# === H2 and Local Dev Options ===
# spring.application.name=IOT_System_DXC
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# === H2 Console ===
#spring.h2.console.enabled=false

# === Devtools & JWT ===
#spring.devtools.restart.enabled=false
#jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

# === Error Handling ===
#server.error.include-message=always
