# Server
spring.datasource.url=jdbc:mysql://db:3306/iot_db
spring.datasource.username=root
spring.datasource.password=secret

spring.data.redis.host=iot_redis
spring.redis.port=6379
# Prevent Spring Security from caching login/register requests
spring.security.request-cache.disable=true

# Make the app stateless to avoid session caching
spring.session.store-type=none


#JWT_SECRET=2FzhFHDm9zK3Kk9UEwvQygYDPoEw7U2kCbZf7pP91pQ=

# Disable default form login
spring.security.formlogin.enabled=false

# Disable session creation (recommended for APIs)
spring.security.sessions=stateless

# Set explicit strategy for path matching
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Enable debug logs
logging.level.org.springframework.security=DEBUG









# === Redis Config ===
#spring.redis.host=redis
#spring.redis.port=6379

# === H2 and Local Dev Options ===
# spring.application.name=IOT_System_DXC
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# === H2 Console ===
#spring.h2.console.enabled=false

# === Devtools & JWT ===
#spring.devtools.restart.enabled=false
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

# === Error Handling ===
#server.error.include-message=always
